### ISSUE TITLE
MODS section greyed out

### ISSUE THREAD

**Issue by AnticOwl** [bl-sdk/willow2-mod-manager#8]
Looks like all Borderlands games were updated.
MODS section is now greyed out. 

Did try BL2 and BL:TPS.

Same behaviour

**Comment by apple1417** [comment]
There hasn't been any update recently. The mod options and mod keybind menus are (intentionally) greyed out if you don't have any mods using them enabled, did you mean that?

**Comment by AnticOwl** [comment]
Let me reinstall the game and check again

**Comment by AnticOwl** [comment]
OK!! I got it now. 

You need to , like you say, enable them on the main menu page.
THEN, only THEN, the option is available!

My bad!

**Comment by AnticOwl** [comment]
All good! It's only me not paying attention.

**Comment by apple1417** [comment]
You're not the only one caught out but, it's a behaviour were changing in the upcoming v3 release

**Comment by AnticOwl** [comment]
I will update my guide with a section describing this. 

And I forgot: thanks for the hard work on this mod.
